In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../Dataset/dataset.csv")

df.drop(columns=["Unnamed: 0"], inplace=True)

df["date"] = pd.to_datetime(df["date"])

df = df.sort_values(["crypto_name", "date"])

df["volatility"] = (df["high"] - df["low"]) / df["open"]

In [3]:
df["daily_return"] = (df["close"] - df["open"]) / df["open"]

In [4]:
df["price_range"] = df["high"] - df["low"]

In [ ]:
df["liquidity_ratio"] = df["volume"] / df["marketCap"]

In [5]:
df["MA7"] = (
    df.groupby("crypto_name")["close"]
      .transform(lambda x: x.rolling(7).mean())
)

In [6]:
df["MA30"] = (
    df.groupby("crypto_name")["close"]
      .transform(lambda x: x.rolling(30).mean())
)

In [7]:
df["rolling_volatility"] = (
    df.groupby("crypto_name")["daily_return"]
      .transform(lambda x: x.rolling(7).std())
)

In [8]:
df["lag_close"] = (
    df.groupby("crypto_name")["close"]
      .shift(1)
)

In [9]:
df = df.dropna()

In [10]:
df.head()

,open,high,low,close,volume,marketCap,timestamp,crypto_name,date,volatility,daily_return,price_range,MA7,MA30,rolling_volatility,lag_close
46058,31.217823,32.900161,29.610259,29.707518,5.863107e+07,3.335160e+08,2020-10-31T23:59:59.999Z,Aave,2020-10-31,0.105385,-0.048380,3.289902,33.032567,40.182902,0.054329,31.217823
46121,29.707518,31.067060,28.494482,30.657276,4.956834e+07,3.454655e+08,2020-11-01T23:59:59.999Z,Aave,2020-11-01,0.086597,0.031970,2.572578,31.997212,41.187592,0.060476,29.707518
46195,30.657282,33.923585,29.344650,29.731524,8.718015e+07,3.353497e+08,2020-11-02T23:59:59.999Z,Aave,2020-11-02,0.149359,-0.030197,4.578936,31.096870,40.406926,0.059793,30.657276
46238,29.731526,30.062917,27.537111,28.042803,5.677501e+07,3.164555e+08,2020-11-03T23:59:59.999Z,Aave,2020-11-03,0.084954,-0.056799,2.525806,30.121337,39.585852,0.060960,29.731524
46250,27.715080,32.303040,25.966155,30.955627,8.521241e+07,3.502055e+08,2020-11-05T23:59:59.999Z,Aave,2020-11-05,0.228644,0.116924,6.336885,29.915844,38.843732,0.078310,28.042803

In [11]:
df.to_csv("../Dataset/processed_crypto.csv", index=False)

In [12]:
processed_crypto.csv

NameError: name 'processed_crypto' is not defined

In [13]:
df.head()

,open,high,low,close,volume,marketCap,timestamp,crypto_name,date,volatility,daily_return,price_range,MA7,MA30,rolling_volatility,lag_close
46058,31.217823,32.900161,29.610259,29.707518,5.863107e+07,3.335160e+08,2020-10-31T23:59:59.999Z,Aave,2020-10-31,0.105385,-0.048380,3.289902,33.032567,40.182902,0.054329,31.217823
46121,29.707518,31.067060,28.494482,30.657276,4.956834e+07,3.454655e+08,2020-11-01T23:59:59.999Z,Aave,2020-11-01,0.086597,0.031970,2.572578,31.997212,41.187592,0.060476,29.707518
46195,30.657282,33.923585,29.344650,29.731524,8.718015e+07,3.353497e+08,2020-11-02T23:59:59.999Z,Aave,2020-11-02,0.149359,-0.030197,4.578936,31.096870,40.406926,0.059793,30.657276
46238,29.731526,30.062917,27.537111,28.042803,5.677501e+07,3.164555e+08,2020-11-03T23:59:59.999Z,Aave,2020-11-03,0.084954,-0.056799,2.525806,30.121337,39.585852,0.060960,29.731524
46250,27.715080,32.303040,25.966155,30.955627,8.521241e+07,3.502055e+08,2020-11-05T23:59:59.999Z,Aave,2020-11-05,0.228644,0.116924,6.336885,29.915844,38.843732,0.078310,28.042803

In [14]:
df.to_csv("../Dataset/processed_crypto.csv", index=False)

print("Saved Successfully!")

Saved Successfully!